#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

timezone=$(cat /etc/timezone)

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
